-- Phase 5: Table Creation with Integrity Constraints

CREATE TABLE departments (
    department_id NUMBER(5) PRIMARY KEY,
    department_name VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE employees (
    employee_id NUMBER(10) PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    hire_date DATE DEFAULT SYSDATE NOT NULL,
    department_id NUMBER(5),
    CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) 
        REFERENCES departments(department_id) ON DELETE SET NULL
);

CREATE TABLE tax_brackets (
    bracket_id NUMBER(5) PRIMARY KEY,
    min_salary NUMBER(10,2) NOT NULL,
    max_salary NUMBER(10,2),
    tax_rate NUMBER(5,2) NOT NULL,
    CONSTRAINT chk_tax_rate CHECK (tax_rate >= 0 AND tax_rate <= 1)
);

CREATE TABLE salaries (
    salary_id NUMBER(10) PRIMARY KEY,
    employee_id NUMBER(10) NOT NULL,
    basic_salary NUMBER(10,2) NOT NULL,
    effective_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_sal_emp FOREIGN KEY (employee_id) 
        REFERENCES employees(employee_id) ON DELETE CASCADE,
    CONSTRAINT chk_basic_sal CHECK (basic_salary > 0)
);

CREATE TABLE payslips (
    payslip_id NUMBER(10) PRIMARY KEY,
    employee_id NUMBER(10) NOT NULL,
    pay_period_month NUMBER(2) NOT NULL,
    pay_period_year NUMBER(4) NOT NULL,
    gross_salary NUMBER(10,2) NOT NULL,
    tax_amount NUMBER(10,2) NOT NULL,
    net_salary NUMBER(10,2) NOT NULL,
    payment_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_pay_emp FOREIGN KEY (employee_id) REFERENCES employees(employee_id),
    CONSTRAINT chk_month CHECK (pay_period_month BETWEEN 1 AND 12)
);

CREATE TABLE public_holidays (
    holiday_id NUMBER(5) PRIMARY KEY,
    holiday_date DATE NOT NULL UNIQUE,
    holiday_name VARCHAR2(100) NOT NULL
);

CREATE TABLE audit_logs (
    log_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50) NOT NULL,
    operation_type VARCHAR2(10) NOT NULL,
    performed_by VARCHAR2(50) DEFAULT USER,
    performed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details VARCHAR2(255)
);